<?php
// fix500.php — patches Composer autoloader after vendor cleanup
// Upload to htdocs root, visit once, delete immediately after
error_reporting(E_ALL);
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);

$root = '/home/vol13_3/infinityfree.com/if0_42397730/htdocs';

echo "<style>body{font-family:monospace;font-size:13px;padding:15px}
h2{color:#155724}h3{color:#856404}pre{background:#f4f4f4;padding:10px;overflow-x:auto;white-space:pre-wrap;word-break:break-all}
.ok{color:green}.bad{color:red}.warn{color:orange}</style>";

echo "<h2>E-Vigilance 500 Fixer</h2>";

// ── 1. Show CI4 error log ─────────────────────────────────────────────────────
echo "<h3>1. CI4 Error Log (last 60 lines)</h3>";
$logDir = $root . '/writable/logs';
$logFiles = glob($logDir . '/log-*.log');
if (empty($logFiles)) {
    echo "<p class='warn'>No log files in $logDir</p>";
} else {
    rsort($logFiles);
    $latest = $logFiles[0];
    $lines = file($latest);
    $tail = array_slice($lines, -60);
    echo "<pre>" . htmlspecialchars(implode('', $tail)) . "</pre>";
}

// ── 2. Show autoload_files.php content ───────────────────────────────────────
echo "<h3>2. vendor/composer/autoload_files.php (current server content)</h3>";
$af = $root . '/vendor/composer/autoload_files.php';
if (file_exists($af)) {
    echo "<pre>" . htmlspecialchars(file_get_contents($af)) . "</pre>";
} else {
    echo "<p class='bad'>File not found: $af</p>";
}

// ── 3. Check which entries in autoload_files.php reference missing files ─────
echo "<h3>3. Checking autoload_files.php entries</h3>";
if (file_exists($af)) {
    $entries = include $af;
    if (is_array($entries)) {
        $missing = [];
        foreach ($entries as $hash => $path) {
            if (!file_exists($path)) {
                $missing[$hash] = $path;
                echo "<p class='bad'>MISSING: $path</p>";
            } else {
                echo "<p class='ok'>OK: $path</p>";
            }
        }
        if (!empty($missing)) {
            // ── 4. Patch autoload_files.php ────────────────────────────────
            echo "<h3>4. Patching autoload_files.php — removing " . count($missing) . " missing entries</h3>";
            $kept = array_diff_key($entries, $missing);
            $out = "<?php\n\n// autoload_files.php \@generated by Composer\n\n\$vendorDir = dirname(__DIR__);\n\$baseDir = dirname(\$vendorDir);\n\nreturn array(\n";
            foreach ($kept as $hash => $path) {
                // Convert absolute path back to relative expression
                $rel = str_replace($root . '/vendor', "    \$vendorDir . '/", $path);
                $rel = str_replace($root, "    \$baseDir . '/", $rel);
                $out .= "    '$hash' => $rel',\n";
            }
            $out .= ");\n";
            if (file_put_contents($af, $out) !== false) {
                echo "<p class='ok'>autoload_files.php patched successfully.</p>";
                echo "<pre>" . htmlspecialchars($out) . "</pre>";
            } else {
                echo "<p class='bad'>Failed to write autoload_files.php — check permissions.</p>";
            }
        } else {
            echo "<p class='ok'>All entries in autoload_files.php point to existing files — not the problem.</p>";
        }
    }
}

// ── 5. Check autoload_static.php for filesMap ────────────────────────────────
echo "<h3>5. autoload_static.php filesMap check</h3>";
$as = $root . '/vendor/composer/autoload_static.php';
if (file_exists($as)) {
    $content = file_get_contents($as);
    // Look for any references to deleted packages
    $deleted = ['fakerphp','phpunit','nikic','sebastian','mikey179','phar-io','myclabs','theseer'];
    $found = [];
    foreach ($deleted as $pkg) {
        if (strpos($content, $pkg) !== false) {
            $found[] = $pkg;
        }
    }
    if (!empty($found)) {
        echo "<p class='warn'>autoload_static.php references deleted packages: " . implode(', ', $found) . "</p>";
        echo "<p>These are in the classmap/PSR4 arrays (lazy-loaded, not fatal). The filesMap is the dangerous one — checking...</p>";
        // Show filesMap portion
        if (preg_match('/public static \$files\s*=\s*array\s*\((.*?)\);/s', $content, $m)) {
            echo "<p><b>filesMap in autoload_static.php:</b></p><pre>" . htmlspecialchars($m[0]) . "</pre>";
        } elseif (preg_match('/public static \$files\s*=\s*\[(.*?)\];/s', $content, $m)) {
            echo "<p><b>filesMap in autoload_static.php:</b></p><pre>" . htmlspecialchars($m[0]) . "</pre>";
        } else {
            echo "<p class='ok'>No static \$files map found (safe).</p>";
        }
    } else {
        echo "<p class='ok'>autoload_static.php has no references to deleted packages.</p>";
    }
} else {
    echo "<p class='bad'>autoload_static.php not found.</p>";
}

// ── 6. Check composer ClassLoader for issues ─────────────────────────────────
echo "<h3>6. Quick PHP fatal check — try requiring autoload</h3>";
ob_start();
$err = null;
set_error_handler(function($no, $str, $file, $line) use (&$err) {
    $err = "Error $no: $str in $file line $line";
    return true;
});
try {
    // We can't re-require autoload.php since we're already running, so just check the file exists
    $autoload = $root . '/vendor/autoload.php';
    if (file_exists($autoload)) {
        echo "<p class='ok'>vendor/autoload.php exists.</p>";
        // Try to parse it for obvious issues
        $ac = file_get_contents($autoload);
        if (strpos($ac, 'autoload_files') !== false) {
            echo "<p class='ok'>autoload.php references autoload_files.php (expected).</p>";
        }
    } else {
        echo "<p class='bad'>vendor/autoload.php MISSING — this would cause 500.</p>";
    }
} catch (Throwable $e) {
    echo "<p class='bad'>Exception: " . htmlspecialchars($e->getMessage()) . "</p>";
}
restore_error_handler();
ob_end_clean();
if ($err) echo "<p class='bad'>$err</p>";

// ── 7. Check .htaccess / index.php ────────────────────────────────────────────
echo "<h3>7. Public entry point check</h3>";
$pubIndex = $root . '/public/index.php';
$rootIndex = $root . '/index.php';
$htaccess = $root . '/.htaccess';
$pubHtaccess = $root . '/public/.htaccess';

foreach ([$pubIndex, $rootIndex, $htaccess, $pubHtaccess] as $f) {
    echo "<p>" . (file_exists($f) ? "<span class='ok'>EXISTS</span>" : "<span class='bad'>MISSING</span>") . ": $f</p>";
}

// Show root .htaccess
if (file_exists($htaccess)) {
    echo "<p><b>.htaccess content:</b></p><pre>" . htmlspecialchars(file_get_contents($htaccess)) . "</pre>";
}

echo "<hr><p style='color:red;font-weight:bold'>DELETE fix500.php from server immediately after viewing this page.</p>";
