<?php
// fix500c.php — writes correct autoload_files.php directly (no string manipulation)
// Upload to htdocs root, visit once, delete immediately.
error_reporting(E_ALL);
ini_set('display_errors', 1);

$root = '/home/vol13_3/infinityfree.com/if0_42397730/htdocs';

echo "<style>body{font-family:monospace;font-size:13px;padding:15px}.ok{color:green}.bad{color:red}pre{background:#f4f4f4;padding:10px;overflow-x:auto;white-space:pre-wrap;word-break:break-all}</style>";
echo "<h2>Fix500c — Direct Autoload File Writer</h2>";

// ── Write correct autoload_files.php from scratch ────────────────────────────
$af = $root . '/vendor/composer/autoload_files.php';

// Only keep the symfony entry (the only one whose file actually exists)
$correct = <<<'PHP'
<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    '6e3fae29631ef280660b3cdad06f25a8' => $vendorDir . '/symfony/deprecation-contracts/function.php',
);
PHP;

if (file_put_contents($af, $correct) !== false) {
    echo "<p class='ok'>autoload_files.php written successfully.</p>";
} else {
    echo "<p class='bad'>FAILED to write autoload_files.php — check permissions.</p>";
}

// ── Verify the file parses correctly ─────────────────────────────────────────
$result = shell_exec('php -l ' . escapeshellarg($af) . ' 2>&1');
if ($result !== null) {
    echo "<p>" . (strpos($result, 'No syntax errors') !== false ? "<span class='ok'>" : "<span class='bad'>") . htmlspecialchars($result) . "</span></p>";
}

// ── Show file content ─────────────────────────────────────────────────────────
echo "<pre>" . htmlspecialchars(file_get_contents($af)) . "</pre>";

// ── Verify autoload_static.php $files (should already be clean from fix500b) ─
$as = $root . '/vendor/composer/autoload_static.php';
$staticContent = file_get_contents($as);
if (preg_match('/public static \$files\s*=\s*array\s*\((.*?)\);/s', $staticContent, $m)) {
    $hasBad = strpos($m[1], 'myclabs') !== false || strpos($m[1], 'phpunit/phpunit') !== false;
    if ($hasBad) {
        echo "<p class='bad'>autoload_static.php \$files still has bad entries — patching now...</p>";
        $badHashes = ['6124b4c8570aa390c21fafd04a26c69f', 'ec07570ca5a812141189b1fa81503674'];
        foreach ($badHashes as $h) {
            $staticContent = preg_replace("/\n?\s*'" . $h . "'\s*=>[^\n]+,?/", '', $staticContent);
        }
        file_put_contents($as, $staticContent);
        echo "<p class='ok'>autoload_static.php re-patched.</p>";
    } else {
        echo "<p class='ok'>autoload_static.php \$files is clean.</p>";
    }
    // Show the files section
    if (preg_match('/public static \$files\s*=\s*array\s*\(.*?\);/s', file_get_contents($as), $m2)) {
        echo "<pre>" . htmlspecialchars($m2[0]) . "</pre>";
    }
}

// ── Final: try fetching the homepage via curl to confirm 200 ─────────────────
echo "<h3>Site check</h3>";
$url = 'https://e-vigilance.freepage.cc/';
$ch = curl_init($url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_TIMEOUT, 10);
curl_setopt($ch, CURLOPT_NOBODY, true); // HEAD request
curl_exec($ch);
$code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
curl_close($ch);
echo "<p>HTTP status of $url: <b>" . ($code == 200 ? "<span class='ok'>$code OK — site is up!</span>" : "<span class='bad'>$code</span>") . "</b></p>";

echo "<hr><p style='color:red;font-weight:bold'>DELETE fix500c.php from server immediately after viewing.</p>";
